modLoader="javafml"
loaderVersion="[37,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="cooperativeadvancements"
version="${file.jarVersion}"
displayName="Cooperative Advancements"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/352568"
logoFile="icon.png"
authors="Grend"
description='''A simple mod to share advancements between all players on a server.'''

[[dependencies.cooperativeadvancements]]
	modId="forge"
	mandatory=true
	versionRange="[37,)"
	ordering="NONE"
	side="SERVER"

[[dependencies.cooperativeadvancements]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.17.1]"
	ordering="NONE"
	side="SERVER"

[[dependencies.cooperativeadvancements]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.0.13,)"
	ordering="NONE"
	side="BOTH"
