modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="cooperativeadvancements"
version="1.1"
displayName="Cooperative Advancements"
displayURL="http://anthonyhilyard.com/"
logoFile="icon.png"
authors="Grend"
description='''A simple mod to share advancements between all players on a server.'''

[[dependencies.cooperativeadvancements]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.cooperativeadvancements]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="SERVER"
